"""initial schema: cases, attempts, audit_logs, processed_webhook_events, stopping_rules_config

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-24

Hand-written (not autogenerated) to match app/models/*.py exactly. If you
add/change a model, add a new revision rather than editing this one.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "cases",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subscription_id", sa.String(128), nullable=False),
        sa.Column("customer_id", sa.String(128), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(8), nullable=False, server_default="INR"),
        sa.Column("status", sa.String(32), nullable=False, server_default="open"),
        sa.Column("failure_category", sa.String(32), nullable=False, server_default="unknown"),
        sa.Column("failure_reason_raw", sa.String(512), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("opted_out", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("source", sa.String(32), nullable=False, server_default="razorpay_webhook"),
        sa.Column("recovered_amount", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_cases_subscription_id", "cases", ["subscription_id"])
    op.create_index("ix_cases_status", "cases", ["status"])

    op.create_table(
        "attempts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("case_id", sa.String(36), sa.ForeignKey("cases.id", ondelete="CASCADE"), nullable=False),
        sa.Column("action_type", sa.String(32), nullable=False),
        sa.Column("result", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(128), nullable=True),
        sa.Column("reason", sa.String(512), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
    )
    op.create_index("ix_attempts_case_id", "attempts", ["case_id"])

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("case_id", sa.String(36), sa.ForeignKey("cases.id", ondelete="CASCADE"), nullable=True),
        sa.Column("event_type", sa.String(32), nullable=False),
        sa.Column("actor", sa.String(32), nullable=False),
        sa.Column("description", sa.String(1024), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
    )
    op.create_index("ix_audit_logs_case_id", "audit_logs", ["case_id"])
    op.create_index("ix_audit_logs_event_type", "audit_logs", ["event_type"])

    op.create_table(
        "processed_webhook_events",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_event_id", sa.String(128), nullable=False),
        sa.Column("event_type", sa.String(32), nullable=False),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column("case_id", sa.String(36), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_processed_webhook_events_provider_event_id",
        "processed_webhook_events",
        ["provider_event_id"],
        unique=True,
    )

    op.create_table(
        "stopping_rules_config",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_category", sa.String(32), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="3"),
        sa.Column("retry_intervals_hours", sa.JSON(), nullable=False),
        sa.Column("max_days_open", sa.Integer(), nullable=False, server_default="7"),
        sa.Column("opt_out_respected", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("failure_category", name="uq_stopping_rules_config_failure_category"),
    )


def downgrade() -> None:
    op.drop_table("stopping_rules_config")
    op.drop_index("ix_processed_webhook_events_provider_event_id", table_name="processed_webhook_events")
    op.drop_table("processed_webhook_events")
    op.drop_index("ix_audit_logs_event_type", table_name="audit_logs")
    op.drop_index("ix_audit_logs_case_id", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_attempts_case_id", table_name="attempts")
    op.drop_table("attempts")
    op.drop_index("ix_cases_status", table_name="cases")
    op.drop_index("ix_cases_subscription_id", table_name="cases")
    op.drop_table("cases")
